# Generated by Django 4.1.7 on 2023-04-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
