# Generated by Django 4.1.7 on 2023-04-21 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='brewery',
            name='country',
            field=models.CharField(default='Polska', max_length=60),
        ),
        migrations.AddField(
            model_name='brewery',
            name='year',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('blg', models.FloatField(blank=True)),
                ('ibu', models.IntegerField(blank=True)),
                ('malt', models.BinaryField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malt'))),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.brewery')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.style')),
            ],
        ),
    ]
