# Generated by Django 4.2.4 on 2023-08-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_image_article_likes_article_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='article',
            name='votes',
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
