# Generated by Django 4.2.4 on 2023-08-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_customuser_is_activated_and_more'),
        ('blog', '0005_category_article_tags_alter_article_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='Like',
        ),
    ]
