# Generated by Django 4.2.4 on 2023-08-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_customuser_pkt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'max_length': 'Podany adres email jest za długi.', 'unique': 'Podany adres email jest już zajęty!'}, max_length=256, unique=True),
        ),
    ]
