# Generated by Django 4.2.4 on 2023-08-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pkt',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
