# Generated by Django 4.2.4 on 2023-08-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_userprofile_pkt_customuser_is_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_activated',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
